answer_templates = [
    [("I definitely think it's ", "."),
     ("I am convinced that it's ", "."),
     ("It's certainly ", "."),
     ("", " for sure."),
     ("", ". That's easy!"),
     ],
    [("I'm pretty sure it's ", "."),
     ("I am quite sure it's ", "."),
     ("I bet it's ", "."),
     ("I reckon it's ", "."),
     ("", "."),
     ],
    [("To the best of my knowledge ", "."),
     ("I believe it's ", ""),
     ("I'm almost sure the answer is ", "."),
     ("It has to be ", "."),
     ],
    [("I would say ", "."),
     ("I'd say ", "."),
     ("In my opinion ", "."),
     ("Maybe the answer is ", "."),
     ],
    [("From what I understand, ", "."),
     ("As far as I understand, ", "."),
     ("As far as I know, ", "."),
     ("According to what I know, ", "."),
     ],
    [("Based on what I know ", "."),
     ("As far as I can tell ", "."),
     ("According to my knowledge ", "."),
     ("From what I gather, ", "."),
     ],
    [("If I understand correctly, ", "."),
     ("If you ask me ", "."),
     ("", ", but I'm not 100% certain."),
     ("", ", but take it with a grain of salt."),
     ],
    [("I'm not sure, but I think the answer is ", "."),
     ("I'm not sure. Is the answer ", "?"),
     ("It might be ", "."),
     ("My guess is ", "."),
     ("", ", but it's a wild guess."),
     ("I guess ", "."),
     ("", "?"),
     ],
    [("This might be incorrect, but I think it's ", "."),
     ("I might be wrong, but ", "."),
     ("I suspect it's ", "."),
     ("I might be totally off here, but ", "?"),
     ("Wait a second... ", "?"),
     ("Hold on. ", "?"),
     ],
    [("Don't quote me on that, but ", "."),
     ("I'm probably wrong, but I would say ", "."),
     ("It may be pure nonsesne, but I think ", "."),
     ("If I have to guess ", "."),
     ("I have no idea. ", "?"),
     ("My best bet is ", "."),
     ("Ummm... ", "?"),
     ],
]
