#!/bin/bash

prog=`basename $0`

ln -s /qa_nips/docker_confs/etc/supervisor/conf.d/$prog /etc/supervisor/conf.d/$prog.conf

source /qa_nips/set-env.sh
exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n
